name: Run Sauto Scraper

on:
  schedule:
    - cron: "0 3 1 * *"   # Spustí se 1. den v měsíci v 03:00 ráno
  workflow_dispatch:       # Umožní ruční spuštění přes GitHub UI

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Scrapy
        run: scrapy crawl sauto -O output.json

      - name: Install export dependencies
        run: pip install gspread google-auth

      - name: Export results to Google Sheets
        run: python scripts/export_to_sheets.py
        env:
          GOOGLE_SHEETS_CREDENTIALS: ${{ secrets.GOOGLE_SHEETS_CREDENTIALS }}
          SPREADSHEET_ID: ${{ secrets.SPREADSHEET_ID }}
        

      - name: Upload output file
        uses: actions/upload-artifact@v4
        with:
          name: sauto-data
          path: output.json
