name: Run Sauto Scraper

on:
  schedule:
    - cron: "0 3 1 * *"   # Spustí se 1. den v měsíci v 03:00 ráno
  workflow_dispatch:       # Umožní ruční spuštění přes GitHub UI

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

            - name: Set params for Hyundai
        run: |
          echo '{
            "limit": "1000",
            "offset": "0",
            "manufacturer_model_seo": "hyundai",
            "condition_seo": "ojete,predvadeci",
            "category_id": "838",
            "operating_lease": "false",
            "price_from": "0",
            "price_step": "200000",
            "price_max": "1500000"
          }' > params.json

      - name: Scrape Hyundai
        run: scrapy crawl sauto -O output_hyundai.json

      - name: Set params for Kia
        run: |
          echo '{
            "limit": "1000",
            "offset": "0",
            "manufacturer_model_seo": "kia",
            "condition_seo": "ojete,predvadeci",
            "category_id": "838",
            "operating_lease": "false",
            "price_from": "0",
            "price_step": "200000",
            "price_max": "1500000"
          }' > params.json

      - name: Scrape Kia
        run: scrapy crawl sauto -O output_kia.json

      - name: Install export dependencies
        run: pip install gspread google-auth

      - name: Export results to Google Sheets
        run: python scripts/export_to_sheets.py
        env:
          GOOGLE_SHEETS_CREDENTIALS: ${{ secrets.GOOGLE_SHEETS_CREDENTIALS }}
          SPREADSHEET_ID: ${{ secrets.SPREADSHEET_ID }}
        

      - name: Upload output file
        uses: actions/upload-artifact@v4
        with:
          name: sauto-data
          path: output.json
